services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assetforge-db-dev
    volumes:
      - ../backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - assetforge-test-network
    ports:
      - 15432:5432

networks:
  assetforge-test-network:
    driver: bridge
