-- Migration Up

ALTER TABLE IF EXISTS t_etf 
ADD scrape_date_base_data DATE,
ADD scrape_date_details DATE,
ADD isin VARCHAR(20),
ADD wkn VARCHAR(20),
ADD nr_positions INT,
ADD base_index TEXT,
ADD share_class_volume VARCHAR(20),
ADD fund_domicile TEXT,
ADD fund_currency VARCHAR(20),
ADD securities_lending_permitted BOOLEAN,
ADD trade_currency VARCHAR(20),
ADD has_currency_hedging BOOLEAN,
ADD has_special_assets BOOLEAN,
ADD fund_provider TEXT,
ADD legal_structure TEXT,
ADD fund_structure TEXT,
ADD administrator TEXT,
ADD depotbank TEXT,
ADD auditor TEXT,
ADD country_composition JSON,
ADD region_composition JSON,
ADD currency_distribution JSON,
ADD weight_top_10 DECIMAL,
ADD nr_stock_positions INT,
ADD nr_bond_positions INT,
ADD nr_cash_and_other_positions INT,
ADD top_10_holdings JSON,
ADD industry_distribution JSON,
ADD activity_distribution JSON,
ADD historical_performance JSON,
ADD historical_volatility JSON,
ADD historical_max_drawdown JSON,
ADD historical_sharpe_ratio JSON,
ADD exchanges JSON

